In [5]:
!pip install category_encoders

Collecting category_encoders
  Downloading category_encoders-2.6.0-py2.py3-none-any.whl (81 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 81.2/81.2 kB 1.6 MB/s eta 0:00:00a 0:00:01
Requirement already satisfied: statsmodels>=0.9.0 in /Users/macbook/anaconda3/lib/python3.10/site-packages (from category_encoders) (0.13.5)
Requirement already satisfied: numpy>=1.14.0 in /Users/macbook/anaconda3/lib/python3.10/site-packages (from category_encoders) (1.23.5)
Requirement already satisfied: scipy>=1.0.0 in /Users/macbook/anaconda3/lib/python3.10/site-packages (from category_encoders) (1.10.0)
Requirement already satisfied: pandas>=1.0.5 in /Users/macbook/anaconda3/lib/python3.10/site-packages (from category_encoders) (1.5.3)
Requirement already satisfied: patsy>=0.5.1 in /Users/macbook/anaconda3/lib/python3.10/site-packages (from category_encoders) (0.5.3)
Requirement already satisfied: scikit-learn>=0.20.0 in /Users/macbook/anaconda3/lib/python3.10/site-packages (from category_encoders) (1.2.1)
Requirement already satisfied: python-dateutil>=2.8.1 in /Users/macbook/anaconda3/lib/python3.10/site-packages (from pandas>=1.0.5->category_encoders) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /Users/macbook/anaconda3/lib/python3.10/site-packages (from pandas>=1.0.5->category_encoders) (2022.7)
Requirement already satisfied: six in /Users/macbook/anaconda3/lib/python3.10/site-packages (from patsy>=0.5.1->category_encoders) (1.16.0)
Requirement already satisfied: joblib>=1.1.1 in /Users/macbook/anaconda3/lib/python3.10/site-packages (from scikit-learn>=0.20.0->category_encoders) (1.1.1)
Requirement already satisfied: threadpoolctl>=2.0.0 in /Users/macbook/anaconda3/lib/python3.10/site-packages (from scikit-learn>=0.20.0->category_encoders) (2.2.0)
Requirement already satisfied: packaging>=21.3 in /Users/macbook/anaconda3/lib/python3.10/site-packages (from statsmodels>=0.9.0->category_encoders) (22.0)
Installing collected packages: category_encoders
Successfully installed category_encoders-2.6.0

In [19]:
import pandas as pd
import numpy as np
from category_encoders import TargetEncoder

TE = TargetEncoder()

data = pd.read_csv('homeprices.csv')
data['town'] = TE.fit_transform(data['town'], data['area']) # mean value of target calculate in this case area

data

           town  area   price
0   3170.570801  2600  550000
1   3170.570801  3000  565000
2   3170.570801  3200  610000
3   3170.570801  3600  680000
4   3170.570801  4000  725000
5   3134.201308  2600  585000
6   3134.201308  2800  615000
7   3134.201308  3300  650000
8   3134.201308  3600  710000
9   3130.001768  2600  575000
10  3130.001768  2900  600000
11  3130.001768  3100  620000
12  3130.001768  3600  695000