In [20]:
# import packages
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler() # modify StandardScaler as scaler


data = pd.read_csv('homeprices.csv')
data 

X = data.drop(['town'], axis = 1) 
scaler.fit_transform(X)

X_train, X_test = train_test_split(X, test_size = 0.2, random_state = 2, shuffle = False )
X_train

test_size = 0.2 takes 20 % to test
random_state = 2 every time if i run the app the results split the same.
shuffle : True or False if true and If i say random state and change value the outcome change
but if I say false even if i change the random state the results stay the same
stratify =  array-like object , by default it is None.

    area   price
1   3000  565000
12  3600  695000
0   2600  550000
7   3300  650000
11  3100  620000
4   4000  725000
6   2800  615000
9   2600  575000
10  2900  600000
5   2600  585000